//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class blood_bag
    {
        public int blood_bag_id { get; set; }
        public Nullable<long> national_id { get; set; }
        public Nullable<System.DateTime> blood_bag_date { get; set; }
        public Nullable<int> blood_camp_id { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public string notes { get; set; }
    
        public virtual shift shift { get; set; }
        public virtual hospital hospital { get; set; }
        public virtual donor donor { get; set; }
    }
}
