//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class donor_health_info
    {
        public long national_id { get; set; }
        public int hospital_id { get; set; }
        public System.DateTime report_date { get; set; }
        public string blood_pressure { get; set; }
        public string glucose_level { get; set; }
        public string notes { get; set; }
    
        public virtual donor donor { get; set; }
        public virtual hospital hospital { get; set; }
    }
}
