//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public donor()
        {
            this.blood_bag = new HashSet<blood_bag>();
            this.donor_health_info = new HashSet<donor_health_info>();
        }
    
        public long national_id { get; set; }
        public string name { get; set; }
        public string gender { get; set; }
        public byte age { get; set; }
        public long phone { get; set; }
        public string city { get; set; }
        public string governorate { get; set; }
        public string blood_type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_bag> blood_bag { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<donor_health_info> donor_health_info { get; set; }
        public virtual user user { get; set; }
    }
}
