//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital_provides_service
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hospital_provides_service()
        {
            this.user_uses_service = new HashSet<user_uses_service>();
        }
    
        public int hospital_id { get; set; }
        public string service_name { get; set; }
        public int value { get; set; }
    
        public virtual hospital hospital { get; set; }
        public virtual service service { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_uses_service> user_uses_service { get; set; }
    }
}
