//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public shift()
        {
            this.blood_bag = new HashSet<blood_bag>();
        }
    
        public int blood_camp_id { get; set; }
        public System.DateTime shift_date { get; set; }
        public string shift_manager_username { get; set; }
        public byte start_hour { get; set; }
        public byte finish_hour { get; set; }
        public string city { get; set; }
        public string governorate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<blood_bag> blood_bag { get; set; }
        public virtual blood_camp blood_camp { get; set; }
        public virtual shift_manager shift_manager { get; set; }
    }
}
