//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_uses_service
    {
        public int service_id { get; set; }
        public Nullable<long> national_id { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public string service_name { get; set; }
        public Nullable<System.DateTime> service_use_date { get; set; }
    
        public virtual hospital_provides_service hospital_provides_service { get; set; }
        public virtual user user { get; set; }
    }
}
